###########################
##                       ##
##      M-Utility        ##
##                       ##
##     by Menshons       ##
##     Version 1.0       ##
##                       ##
###########################

MYSQL:
  Table prefix: 'game_mutility_'
  Host: '109.164.104.180'
  Port: '3306'
  Database: 'newkostkuj'
  User: 'superadmin'
  Password: 'kostkujjede'

  # Table prefix: 'game_mutility_'
  # Host: '109.164.104.180'
  #  Port: '3306'
  #  Database: 'newkostkuj'
  #  User: 'superadmin'
  #  Password: 'kostkujjede'

  # Table prefix: 'game_mutility_'
  # Host: '${KMC_DB_HOST}'
  # Port: ${KMC_DB_PORT}
  # Database: '${KMC_DB_DATABASE}'
  # User: '${KMC_DB_USER}'
  # Password: '${KMC_DB_PASSWORD}'

Colors:
  Chat:
    Primary: '#1eb0ff'
    Secondary: '#B5C2C5'
    Third: '#55FFFF'
    Disable: '#637C7E'
  Console:
    Primary: '3'
    Secondary: '7'
