name: MUtility
version: ${project.version}
main: com.mens.mutility.spigot.MUtilitySpigot
api-version: 1.16
authors: [ Menshons ]
description: Plugin dodatečných funkcí určený exkluzivně pro server Kostkuj.cz
commands:
  mstavba:
    description: Stavba mesice
permissions:
  mutility.stavba:
    default: op
    description: Napoveda ke stavbe mesice