name: MUtility
version: ${project.version}
main: com.mens.mutility.spigot.MUtilitySpigot
api-version: 1.16
authors: [ Menshons ]
description: Plugin dodatečných funkcí určený exkluzivně pro server Kostkuj.cz
commands:
  mutility:
    description: Sprava pluginu
  mstavba:
    description: Stavba mesice
  event:
    description: Eventy
  mresidence:
    description: Residence zprava
  mres:
    description: Residence zprava
  minv:
    description: Inventare
  anketa:
    description: Ankety
  zalohy:
    description: Zalohy
  navrhy:
    description: Navrhy
permissions:
  mutility.help:
    default: op
    description: Napoveda k pluginu
  mutility.reload:
    default: op
    description: Reload pluginu
  mutility.stavba.help:
    default: op
    description: Napoveda ke stavbe mesice
  mutility.stavba.manage:
    default: op
    description: Sprava stavby mesice
  mutility.stavba.create:
    default: op
    description: Vytvareni stavby mesice
  mutility.stavba.vote:
    default: op
    description: Hlasovani ve stavbe mesice
  mutility.eventy.help:
    default: op
    description: Napoveda k eventum
  mutility.eventy.otazky.create:
    default: op
    description: Vytvareni otazek k eventu Ano/Ne
  mutility.eventy.create:
    default: op
    description: Vytvareni eventu
  mutility.eventy.manage:
    default: op
    description: Sprava eventu
  mutility.eventy.hledacka.create:
    default: op
    description: Vytvareni eventu Hledacka
  mutility.eventy.hrbitov.create:
    default: op
    description: Vytvareni eventu Hrbitov
  mutility.eventy.message:
    default: op
    description: Posilani zprav o eventech
  mutility.eventy.tp:
    default: op
    description: Teleportace na eventy
  mutility.eventy.delete:
    default: op
    description: Mazani eventu
  mutility.eventy.otazky.reset:
    default: op
    description: Reset eventu Ano/Ne
  mutility.eventy.otazky.vote:
    default: op
    description: Hlasovani v eventu Ano/Ne
  mutility.eventy.disableflybypass:
    default: op
    description: Nevypne fly pri teleportaci
  mutility.residence.help:
    default: op
    description: Napoveda k prikazu MRes
  mutility.residence.send:
    default: op
    description: Poslani residence zpravy
  mutility.inventory.help:
    default: op
    description: Napoveda k prikazu MInv
  mutility.inventory.save:
    default: op
    description: Ukladani inventare
  mutility.inventory.load:
    default: op
    description: Nacitani inventare
  mutility.inventory.delete:
    default: op
    description: Mazani inventare
  mutility.inventory.manage:
    default: op
    description: Sprava inventare
  mutility.inventory.show:
    default: op
    description: Zobrazeni inventare
  mutility.anketa.help:
    default: op
    description: Napoveda k anketam
  mutility.anketa.create:
    default: op
    description: Vytvareni ankety
  mutility.anketa.add:
    default: op
    description: Pridavani moznosti do ankety
  mutility.anketa.run:
    default: op
    description: Spousteni a vypinani ankety
  mutility.zalohy.help:
    default: op
    description: Napoveda k zaloham
  mutility.zalohy.create:
    default: op
    description: Vytvareni zaloh
  mutility.zalohy.manage:
    default: op
    description: Sprava zaloh
  mutility.zalohy.admin:
    default: op
    description: Sprava ostatnich zaloh
  mutility.zalohy.delete:
    default: op
    description: Mazani zaloh
  mutility.navrhy.help:
    default: op
    description: Napoveda k navrhum
  mutility.navrhy.add:
    default: op
    description: Pridavani navrhu
  mutility.navrhy.show:
    default: op
    description: Seznam hracovych navrhu
  mutility.navrhy.delete:
    default: op
    description: Smazani navrhu
  mutility.navrhy.admin:
    default: op
    description: Vraceni nevyrizenych navrhu
  mutility.navrhy.accept:
    default: op
    description: Schvalovani navrhu
  mutility.navrhy.reject:
    default: op
    description: Zamitani navrhu
  mutility.navrhy.return:
    default: op
    description: Vraceni zamitnuteho navrhu do nevyrizenych
  mutility.navrhy.manage:
    default: op
    description: Uprava navrhu





