###########################
##                       ##
##      M-Utility        ##
##                       ##
##     by Menshons       ##
##     Version 1.0       ##
##                       ##
###########################

Servers:
  OverWorld 1:
    Name: 'server1'
    LoadPlayerData: true
    Center:
      X: -50000
      Z: 50000
    Radius: 50000
    TP border 1:
      From:
        X: -100
        Z: 0
      To:
        x: 0
        Z: 100000
    TP border 2:
      From:
        X: -100000
        Z: 0
      To:
        x: 0
        Z: 100

  OverWorld 2:
    Name: 'server2'
    LoadPlayerData: true
    Center:
      X: -50000
      Z: -50000
    Radius: 50000
    TP border 1:
      From:
        X: -100
        Z: -100000
      To:
        x: 0
        Z: 0
      TP border 2:
        From:
          X: -100000
          Z: 0
        To:
          x: 0
          Z: 100

  OverWorld 3:
    Name: 'server3'
    LoadPlayerData: true
    Center:
      X: 50000
      Z: 50000
    Radius: 50000
    TP border 1:
      From:
        X: 0
        Z: 0
      To:
        x: 100
        Z: 100000
      TP border 2:
        From:
          X: 0
          Z: 0
        To:
          x: 100000
          Z: 100

  OverWorld 4:
    Name: 'server4'
    LoadPlayerData: true
    Center:
      X: 50000
      Z: -50000
    Radius: 50000
    TP border 1:
      From:
        X: 0
        Z: -100000
      To:
        x: 100
        Z: 0
      TP border 2:
        From:
          X: 0
          Z: -100
        To:
          x: 100000
          Z: 0

  Lobby:
    Name: 'lobby'
    LoadPlayerData: true
    Center:
      X: 0
      Z: 0
    Radius: 1000

  Nether:
    Name: 'nether'
    LoadPlayerData: true
    Center:
      X: 0
      Z: 0
    Radius: 25000

  End:
    Name: 'end'
    LoadPlayerData: true
    Center:
      X: 0
      Z: 0
    Radius: 25000

  Event:
    Name: 'event'
    LoadPlayerData: false
    Center:
      X: 0
      Z: 0
    Radius: 25000

Colors:
  Chat:
    Primary: '#1eb0ff'
    Secondary: '#B5C2C5'
    Third: '#55FFFF'
    Disable: '#637C7E'
  Console:
    Primary: '3'
    Secondary: '7'
